---
title: "Analysis of TCGA RPPA LIHC samples"
author: "Jovan Tanevski"
date: "`r Sys.Date()`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
```{r include = FALSE}
knitr::opts_chunk$set(dev = "svg")
```


## Setup

Load required libraries.

```{r setup}

library(tidyverse)
library(skimr)
library(uwot)
library(factoextra)
library(cowplot)
```

Read filtered TCGA RRPA data and display summary statistics.

```{r}
tcga <- read_csv("data/TCGA-RPPA-LIHC_selected.csv", col_types = cols()) %>%
  select(-TumorType) %>%
  column_to_rownames("SampleID")
skim(tcga)
```


## Unsupervised analysis

Perform hierarchical clustering of the data and plot the resulting dendrogram

```{r fig.width=16, fig.height=9}
tcga.hclust <- eclust(tcga, "hclust", k = 4)

fviz_dend(tcga.hclust, rect = TRUE)

fviz_silhouette(tcga.hclust) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

Project to 2D with PCA and UMAP and plot

```{r}
tcga.pca <- prcomp(tcga)
summary(tcga.pca)

fviz_pca_biplot(tcga.pca, label = "var", col.ind = as.factor(tcga.hclust$cluster)) +
  theme_classic()

tcga.umap <- umap(tcga, n_neighbors = 5, n_epochs = 1000) %>%
  cbind(tcga.hclust$cluster) %>%
  `colnames<-`(c("U1", "U2", "Cluster")) %>%
  as_tibble() %>%
  mutate_at("Cluster", as.factor)

ggplot(tcga.umap, aes(x = U1, y = U2, color = Cluster, shape = Cluster)) +
  geom_point() +
  theme_classic()
```

Expression profiles per cluster 

```{r fig.width=10, fig.height=10}
tcga.clustered <- tcga %>%
  mutate(Cluster = as.factor(tcga.hclust$cluster)) %>%
  pivot_longer(names_to = "Marker", values_to = "Z", -Cluster)

profiles <- seq_len(4) %>% map(~
ggplot(
  tcga.clustered %>% filter(Cluster == .x),
  aes(x = Marker, y = Z, color = Marker)
) +
  stat_summary(fun.data = mean_sdl, show.legend = FALSE) +
  ylim(-3, 3) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)))

plot_grid(plotlist = profiles, labels = paste("Cluster", seq_len(4)))
```
